# Site settings
title: Polar Bear
email: jo639@kookmin.ac.kr
description: > # this means to ignore newlines until "baseurl:"
  Jekyll Theme Demo
baseurl: "https://jo639.github.io/" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: username
github_username: jo639

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]